# Generated by Django 3.2.23 on 2024-01-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('date', models.DateField()),
                ('bloodgroup', models.CharField(max_length=45)),
                ('bystandername', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
    ]
