# Generated by Django 3.2.23 on 2024-01-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('adm_no', models.CharField(max_length=45)),
                ('course', models.CharField(max_length=45)),
                ('year', models.CharField(max_length=45)),
                ('dob', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('bloodgroup', models.CharField(max_length=45)),
                ('photo', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
